contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
title = "immigrant sheep of doom"
author = "immigrantsheep"
copyright = "immigrantsheep All rights reserved."
canonifyurls = true
baseurl = "http://immigrantsheep.github.io"